export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_SELECTED_EVENT = 'FETCH_SELECTED_EVENT';
export const CLEAR_SELECTED_EVENT = 'CLEAR_SELECTED_EVENT';
export const TOGGLE_JOIN_EVENT = 'TOGGLE_JOIN_EVENT';
export const FETCH_ALL_EVENTS = 'FETCH_ALL_EVENTS';
