export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_SELECTED_EVENT = 'FETCH_SELECTED_EVENT';
export const CLEAR_SELECTED_EVENT = 'CLEAR_SELECTED_EVENT';
export const FETCH_EVENT_ATTENDEES = 'FETCH_EVENT_ATTENDEES';
export const FETCH_ALL_EVENTS = 'FETCH_ALL_EVENTS';
export const ATTEND_EVENT = 'ATTEND_EVENT';
export const LEAVE_EVENT = 'LEAVE_EVENT';
