export const FETCH_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS';
export const FETCH_GROUP_SUCCESS = 'FETCH_GROUP_SUCCESS';
export const JOIN_GROUP_SUCCESS = 'JOIN_GROUP_SUCCESS';
export const LEAVE_GROUP_SUCCESS = 'LEAVE_GROUP_SUCCESS';
