export const SET_USER_SUCCESS = 'SET_USER';
export const SET_USER_LOADING = 'SET_USER_LOADING';
export const SET_USER_FAILURE = 'SET_USER_FAILURE';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';

export const LEAVE_GROUP_SUCCESS = 'LEAVE_GROUP_SUCCESS';
export const JOIN_GROUP_SUCCESS = 'JOIN_GROUP_SUCCESS';
